server:
  port: 2021

spring:
  application:
    name: nacos-gateway
  #redis配置
  redis:
    database: 0
    host: 192.168.2.11
    port: 6379
    password: root
    jedis:
      pool:
        max-active: 200
        max-wait: -1ms
        max-idle: 10
        min-idle: 0
    timeout: 10000s

  #网关配置
  cloud:
    gateway:
      routes:
        - id: nacos-consumer-a # 服务名spring.application.name
          uri: lb://nacos-consumer-a
          predicates:
            - Path=/nacos-consumer-a/**
        - id: nacos-provider-a
          uri: lb://nacos-provider-a
          predicates:
            - Path=/nacos-provider-a/**
      discovery:
        locator:
          enabled: true #表明gateway开启服务注册和发现的功能，并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router，这个router将以服务名开头的请求路径转发到对应的服务。


jwt:
  secret: Mars-Cloud
  key:
    userId: USER_ID
    token: TOKEN
    roleIdList: ROLE_ID_LIST
